[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # GitHub configuration - replace with your actual values
  GITHUB_REPO_OWNER = "your-github-username"
  GITHUB_REPO_NAME = "your-repository-name"
  GITHUB_DOCS_PATH = "docs"
  # GITHUB_TOKEN = "your-github-token-here"  # Uncomment for private repos

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"