[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# CRITICAL: API redirects must come BEFORE the catch-all redirect
# These redirects map /api/* to Netlify functions
[[redirects]]
  from = "/api/docs/info"
  to = "/.netlify/functions/docs-info"
  status = 200
  force = true

[[redirects]]
  from = "/api/docs/tree"
  to = "/.netlify/functions/docs-tree"
  status = 200
  force = true

[[redirects]]
  from = "/api/docs/file"
  to = "/.netlify/functions/docs-file"
  status = 200
  force = true

[[redirects]]
  from = "/api/markdown/parse"
  to = "/.netlify/functions/markdown-parse"
  status = 200
  force = true

# Catch-all redirect for SPA routing (must be LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Headers for better performance and security
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"