[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  
  # GitHub configuration (optional - for GitHub integration)
  # Replace with your actual values or set in Netlify dashboard
  # GITHUB_REPO_OWNER = "your-github-username"
  # GITHUB_REPO_NAME = "your-repository-name"
  # GITHUB_DOCS_PATH = "docs"
  # GITHUB_TOKEN = "your-github-token-here"  # Only for private repos

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Optional: Add a docs folder to your repository for local docs
# This will be used as the primary source, with GitHub as fallback